# Generated by Django 5.1.15 on 2026-09-06 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_period_start', models.DateTimeField()),
                ('snapshot_period_end', models.DateTimeField()),
                ('attendance_rate', models.FloatField()),
                ('late_attendance_count', models.IntegerField()),
                ('lesson_replay_completion', models.FloatField(default=0.0)),
                ('quiz_score_avg', models.FloatField(default=0.0)),
                ('recent_engagement_score', models.FloatField(default=0.0)),
                ('session_participation_count', models.IntegerField(default=0)),
                ('trend_vs_previous', models.FloatField(default=0.0)),
                ('feature_schema_version', models.CharField(default='v1.0', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Feature Snapshot',
                'verbose_name_plural': 'Feature Snapshots',
            },
        ),
        migrations.CreateModel(
            name='InterventionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('action_plan', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention Case',
                'verbose_name_plural': 'Intervention Cases',
            },
        ),
        migrations.CreateModel(
            name='InterventionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intervention_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ews.interventioncase')),
            ],
            options={
                'verbose_name': 'Intervention Note',
                'verbose_name_plural': 'Intervention Notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('training_data_description', models.TextField()),
                ('feature_schema_version', models.CharField(max_length=50)),
                ('training_metrics', models.JSONField()),
                ('approval_status', models.CharField(choices=[('draft', 'Draft / Evaluating'), ('approved', 'Approved'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
            },
        ),
        migrations.CreateModel(
            name='NotificationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drafts', to=settings.AUTH_USER_MODEL)),
                ('intervention_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_drafts', to='ews.interventioncase')),
            ],
            options={
                'verbose_name': 'Notification Draft',
                'verbose_name_plural': 'Notification Drafts',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(help_text='Risk score from 0 to 100')),
                ('risk_band', models.CharField(choices=[('routine', 'Routine'), ('review', 'Review'), ('priority', 'Priority')], max_length=20)),
                ('top_contributing_factors', models.JSONField(help_text='Key features driving the score')),
                ('model_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_planned', 'Action Planned')], default='pending_review', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feature_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ews.featuresnapshot')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ews.modelversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
            },
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='risk_assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_case', to='ews.riskassessment'),
        ),
    ]
