# Generated by Django 5.1.15 on 2026-09-06 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(help_text='Engagement score out of 100')),
                ('attendance_rate', models.FloatField(help_text='Percentage of attended sessions')),
                ('participation_count', models.IntegerField(default=0, help_text='Number of in-class interactions')),
                ('calculation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='academics.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Engagement Metric',
                'verbose_name_plural': 'Engagement Metrics',
                'ordering': ['-calculation_timestamp'],
            },
        ),
    ]
