# Generated by Django 5.1.15 on 2026-09-06 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='class_sessions.classsession')),
            ],
            options={
                'verbose_name': 'Session Event',
                'verbose_name_plural': 'Session Events',
                'ordering': ['created_at'],
            },
        ),
    ]
